### ISSUE TITLE
ModuleNotFoundError: No module named 'wpilib.command.subsystem'

### ISSUE THREAD

**Issue by CrispyBacon1999** [robotpy/robotpy-commands-v1#4]
Can't import the subsystem class when working with the examples/command-based robot.

**Comment by CrispyBacon1999** [comment]
Seems to be an issue with the code that was already there having an issue, but not having command based experience in past years, I don't know if it was an issue before.

**Comment by virtuald** [comment]
You need to do `from wpilib.command import Subsystem`

**Comment by CrispyBacon1999** [comment]
I found that out with some fiddling, is that what the syntax was in previous years and the examples were just out of date?

**Comment by auscompgeek** [comment]
It's always been documented as `wpilib.command.Subsystem`.

**Comment by CrispyBacon1999** [comment]
Code hadn't been modified since 2016, I can definitely see that being an issue. Easy enough fix though.

**Comment by virtuald** [comment]
In previous years, both worked. It's really annoying to make both work this year, so I'd rather not bother fixing it.
