### ISSUE TITLE
Scheduler is not Sendable

### ISSUE THREAD

**Issue by restouffer** [robotpy/robotpy-commands-v1#6]
Attempting to add Scheduler to the SmartDashboard with

```
SmartDashboard.putData('Active Commands', Scheduler.getInstance())
```

fails with the message

```
TypeError: putData(): incompatible function arguments. The following argument types are supported:
    1. (key: str, data: wpilib._wpilib.Sendable) -> None
    2. (value: wpilib._wpilib.Sendable) -> None
```

According to the [C++ documentation](https://first.wpi.edu/FRC/roborio/release/docs/cpp/classfrc_1_1Scheduler.html), Scheduler should extend Sendable

**Comment by virtuald** [comment]
Looks like I explicitly ignore it for some reason (https://github.com/robotpy/robotpy-commands-v1/blob/7898ff9e13849604c464c12d8f346a64e6fe18a3/gen/Scheduler.yml#L18). However, I rebuilt it locally with that taken out and it still doesn't work.

How important is this?

**Comment by virtuald** [comment]
Oh, I forgot to reinstall the wheel. Now I can see why I ignored the base:

```
>>> import wpilib.command
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/virtuald/.virtualenvs/frc-2020/lib/python3.7/site-packages/wpilib/command/__init__.py", line 4, in <module>
    from ._commands_v1 import (
ImportError: generic_type: type "Scheduler" does not have a non-default holder type while its base "frc::Sendable" does
```
This is going to be difficult to fix, so how important is this?

**Comment by restouffer** [comment]
I would classify it as a nice-to-have. It's handy to see the currently running commands on the dashboard, but my team can get along without it.

**Comment by auscompgeek** [comment]
Does Scheduler not add itself to LiveWindow?

**Comment by virtuald** [comment]
I tried to hack at this again and wasn't able to make it work. As a workaround, I made a separate static method for doing this (addToSmartDashboard).
